theme = "dracula"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
format = "{icon} / {available}"
unit = "GB"
interval = 30
alert = 10
warning = 5
on_click = "exec pcmanfm /"

[[block]]
block = "disk_space"
path = "/home"
format = "{icon} /home {available}"
unit = "GB"
interval = 30
alert = 10
warning = 5
on_click = "exec pcmanfm ${HOME}"
[block.icons_overrides]
disk_drive = "\ue065"

[[block]]
block = "cpu"
format = "{utilization}"
interval = 1
on_click = "alacritty --class htop -t htop -e htop"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
interval = 5
clickable = true
[block.icons_overrides]
memory_mem = "\uf538"
memory_swap = "\uf1b2"

[[block]]
block = "net"
device = "ens3"
format = "{speed_down;K*b}"
format_alt = "{speed_up;K*b}"
interval = 5

[[block]]
block = "time"
format = "%I:%M %p"
interval = 1
